### ISSUE TITLE
node-gyp rebuild failed

### ISSUE THREAD

**Issue by TroubleChenC** [node-ffi-napi/node-ffi-napi#275] opened 2024-06-04 03:20 UTC
OS:win11
node -v v20.14.0
vs2022 community
run npm install ffi-napi:

$ npm install ffi-napi
npm warn deprecated gar@1.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm error code 1
npm error path D:\work\code\electron\excel2html_vue3\node_modules\ffi-napi
npm error command failed
npm error command C:\windows\system32\cmd.exe /d /s /c node-gyp-build
npm error nothing.c
npm error   win_delay_load_hook.cc
npm error   nothing.vcxproj -> D:\work\code\electron\excel2html_vue3\node_modules\ffi-napi\build\Release\\nothing.lib
npm error   Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
npm error   win64_intel.preasm
npm error   Building assembly file Release\obj\ffi\\win64_intel.asm
npm error    Assembling: Release\obj\ffi\win64_intel.asm
npm error   prep_cif.c
npm error   types.c
npm error   raw_api.c
npm error   java_raw_api.c
npm error   closures.c
npm error   ffiw64.c
npm error   win_delay_load_hook.cc
npm error   ffi.vcxproj -> D:\work\code\electron\excel2html_vue3\node_modules\ffi-napi\build\Release\\libffi.lib 
npm error   ffi.cc
npm error D:\work\code\electron\excel2html_vue3\node_modules\get-uv-event-loop-napi-h\include\get-uv-event-loop-napi.h(26,30): error C2440: “=”: 无法从“napi_status (__cdecl *)(node_api_nogc_env,uv_loop_s **)”转换为“get_uv_event_loop_fn” [D:\work\code\electron\excel2html_vue3\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
npm error   (编译源文件“../src/ffi.cc”)
npm error   D:\work\code\electron\excel2html_vue3\node_modules\get-uv-event-loop-napi-h\include\get-uv-event-loop-napi.h(26,30):
npm error   此转换需要 reinterpret_cast、C 样式强制转换或带圆括号函数样式强制转换
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@9.4.1
npm error gyp info using node@20.14.0 | win32 | x64
npm error gyp info find Python using Python version 3.10.0 found at "C:\Program Files\Python310\python.exe"      
npm error gyp info find VS using VS2022 (17.9.34723.18) found at:
npm error gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm error gyp info find VS run with --verbose for detailed information
npm error gyp info spawn C:\Program Files\Python310\python.exe
npm error gyp info spawn args [
npm error gyp info spawn args   'D:\\work\\code\\electron\\excel2html_vue3\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm error gyp info spawn args   'binding.gyp',
npm error gyp info spawn args   '-f',
npm error gyp info spawn args   'msvs',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   'D:\\work\\code\\electron\\excel2html_vue3\\node_modules\\ffi-napi\\build\\config.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   'D:\\work\\code\\electron\\excel2html_vue3\\node_modules\\node-gyp\\addon.gypi', 
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   'C:\\Users\\chenc\\AppData\\Local\\node-gyp\\Cache\\20.14.0\\include\\node\\common.gypi',
npm error gyp info spawn args   '-Dlibrary=shared_library',
npm error gyp info spawn args   '-Dvisibility=default',
npm error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\chenc\\AppData\\Local\\node-gyp\\Cache\\20.14.0',    
npm error gyp info spawn args   '-Dnode_gyp_dir=D:\\work\\code\\electron\\excel2html_vue3\\node_modules\\node-gyp',
npm error gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\chenc\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.14.0\\\\<(target_arch)\\\\node.lib',
npm error gyp info spawn args   '-Dmodule_root_dir=D:\\work\\code\\electron\\excel2html_vue3\\node_modules\\ffi-napi',
npm error gyp info spawn args   '-Dnode_engine=v8',
npm error gyp info spawn args   '--depth=.',
npm error gyp info spawn args   '--no-parallel',
npm error gyp info spawn args   '--generator-output',
npm error gyp info spawn args   'D:\\work\\code\\electron\\excel2html_vue3\\node_modules\\ffi-napi\\build',      
npm error gyp info spawn args   '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe 
npm error gyp info spawn args [
npm error gyp info spawn args   'build/binding.sln',
npm error gyp info spawn args   '/clp:Verbosity=minimal',
npm error gyp info spawn args   '/nologo',
npm error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm error gyp info spawn args ]
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm error gyp ERR! stack     at ChildProcess.onExit (D:\work\code\electron\excel2html_vue3\node_modules\node-gyp\lib\build.js:203:23)
npm error gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Windows_NT 10.0.22631
npm error gyp ERR! command "C:\\Users\\chenc\\AppData\\Local\\fnm_multishells\\24832_1717470167728\\node.exe" "D:\\work\\code\\electron\\excel2html_vue3\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm error gyp ERR! cwd D:\work\code\electron\excel2html_vue3\node_modules\ffi-napi
npm error gyp ERR! node -v v20.14.0
npm error gyp ERR! node-gyp -v v9.4.1
npm error gyp ERR! not ok

**Comment by cclauss** [comment] 2024-06-04 03:25
Duplicate of #269 and #270 -- Windows users need to run on Node.js v16 or less.
* #269
* #270

**Comment by TroubleChenC** [comment] 2024-06-04 03:27
Windows users need to run on Node.js v16 or less.

**Closed as completed** 2024-06-04 03:27 UTC
