### ISSUE TITLE
Mac下使用ffi-napi出错：vue-router.esm.js?8c4f:2181 Error: No native build was found for platform=darwin arch=x64 runtime=electron abi=73 uv=1 libc=glibc

### ISSUE THREAD

**Issue by feitianlee** [node-ffi-napi/node-ffi-napi#86] opened 2020-06-28 10:20 UTC
vue-router.esm.js?8c4f:2181 Error: No native build was found for platform=darwin arch=x64 runtime=electron abi=73 uv=1 libc=glibc
    at Function.load.path (index.js?04e8:56)
    at load (index.js?04e8:21)
    at eval (ref.js?4c6b:8)
    at Object../node_modules/ref-napi/lib/ref.js (vendor.js:16681)
    at __webpack_require__ (main.js:854)
    at fn (main.js:151)
    at eval (ffi.js?8d23:7)
    at Object../node_modules/ffi-napi/lib/ffi.js (vendor.js:13874)
    at __webpack_require__ (main.js:854)
    at fn (main.js:151)

使用方式按照文档来的。 安装了所有需要的。 同时本机环境正常。 也有command line tools, clang, clang++,make等。

**Comment by addaleax** [comment] 2020-06-29 22:45
I’ll close this as a duplicate of #75

**Closed by addaleax** 2020-06-29 22:45 UTC
