### ISSUE TITLE
node-gyp-build fail for arm64 with electron 11.2.2

### ISSUE THREAD

**Issue by hurryhuang1007** [node-ffi-napi/node-ffi-napi#130] opened 2021-02-05 11:13 UTC
hi, I have some problems when I use electron 11.2.2 to adaptation M1 mac.

my macos version is 11.2, xcode version is 12.4

This is an error message from the console.

```log

  • electron-builder  version=22.10.4 os=20.3.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=build/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=display-info@0.0.1, electron-acrylic-window@0.3.3, ffi-napi@3.1.0, ref-napi@2.1.2 platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=11.2.2 appOutDir=build/mac-universal-x64
  • rebuilding native dependencies  dependencies=display-info@0.0.1, electron-acrylic-window@0.3.3, ffi-napi@3.1.0, ref-napi@2.1.2 platform=darwin arch=arm64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path /Users/hurry/Documents/workspace/ifonts_client_main/node_modules/ffi-napi
    npm ERR! command failed
    npm ERR! command sh -c node-gyp-build
    npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
    npm ERR!   LIBTOOL-STATIC Release/nothing.a
    npm ERR!   CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@7.1.0
    npm ERR! gyp info using node@14.15.4 | darwin | x64
    npm ERR! gyp info find Python using Python version 3.7.5 found at "/usr/local/opt/python/bin/python3.7"
    npm ERR! gyp info spawn /usr/local/opt/python/bin/python3.7
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/Users/hurry/Documents/workspace/ifonts_client_main/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/hurry/Documents/workspace/ifonts_client_main/node_modules/ffi-napi/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/hurry/Documents/workspace/ifonts_client_main/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/hurry/.electron-gyp/11.2.2/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/hurry/.electron-gyp/11.2.2',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/hurry/Documents/workspace/ifonts_client_main/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/hurry/.electron-gyp/11.2.2/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/hurry/Documents/workspace/ifonts_client_main/node_modules/ffi-napi',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info spawn make
    npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    npm ERR! warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
    npm ERR! ../deps/libffi/src/prep_cif.c:26:10: fatal error: 'ffi.h' file not found
    npm ERR! #include <ffi.h>
    npm ERR!          ^~~~~~~
    npm ERR! 1 error generated.
    npm ERR! make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
    npm ERR! gyp ERR! build error 
    npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/hurry/Documents/workspace/ifonts_client_main/node_modules/node-gyp/lib/build.js:194:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    npm ERR! gyp ERR! System Darwin 20.3.0
    npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/hurry/Documents/workspace/ifonts_client_main/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    npm ERR! gyp ERR! cwd /Users/hurry/Documents/workspace/ifonts_client_main/node_modules/ffi-napi
    npm ERR! gyp ERR! node -v v14.15.4
    npm ERR! gyp ERR! node-gyp -v v7.1.0
    npm ERR! gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/hurry/.npm/_logs/2021-02-05T10_43_30_445Z-debug.log
    
                    command=/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js rebuild display-info@0.0.1 electron-acrylic-window@0.3.3 ffi-napi@3.1.0 ref-napi@2.1.2
                    workingDir=
npm ERR! code 1
npm ERR! path /Users/hurry/Documents/workspace/ifonts_client_main
npm ERR! command failed
npm ERR! command sh -c npm run gulp && electron-builder --universal && node .script/md5-dmg.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hurry/.npm/_logs/2021-02-05T10_43_30_503Z-debug.log

```

**Comment by KishanBagaria** [comment] 2021-02-05 18:09
dupe of #118

**Closed** 2021-02-20 04:14 UTC
